// <auto-generated />
using System;
using Books.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Books.Infrastructure.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20230516182609_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Books.Domain.BookAggregate.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5485c003-57cc-4628-a1b8-34ccbe35c587"),
                            CreatedBy = "jcaesar",
                            CreatedOn = new DateTime(2008, 3, 10, 11, 27, 0, 0, DateTimeKind.Unspecified),
                            Description = "The first book in the series, introducing the world of Westeros and its political intrigues.",
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("7c838a53-cac5-4ebe-94cb-c9b46c537c4e"),
                            CreatedBy = "ldavinci",
                            CreatedOn = new DateTime(2006, 3, 24, 18, 33, 0, 0, DateTimeKind.Unspecified),
                            Description = "Continues the story as multiple claimants vie for the Iron Throne.",
                            Title = "A Clash of Kings"
                        },
                        new
                        {
                            Id = new Guid("0881e81c-fbfc-47ff-bc0d-5670aca11601"),
                            CreatedBy = "aeinstein",
                            CreatedOn = new DateTime(2002, 4, 16, 2, 28, 0, 0, DateTimeKind.Unspecified),
                            Description = "The power struggles intensify as war engulfs the Seven Kingdoms.",
                            Title = "A Storm of Swords"
                        },
                        new
                        {
                            Id = new Guid("7ca4a6d0-1f6d-4bd5-9d60-16e48a39563b"),
                            CreatedBy = "ldavinci",
                            CreatedOn = new DateTime(2014, 6, 21, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explores the aftermath of the previous conflicts and the shifting power dynamics.",
                            Title = "A Feast for Crows"
                        },
                        new
                        {
                            Id = new Guid("9407e459-042d-48f0-a9ec-3abf49b81649"),
                            CreatedBy = "aalexander",
                            CreatedOn = new DateTime(2021, 3, 24, 8, 36, 0, 0, DateTimeKind.Unspecified),
                            Description = "Continues the storylines of various characters as conflicts escalate.",
                            Title = "A Dance with Dragons"
                        },
                        new
                        {
                            Id = new Guid("8f33b67c-5080-4132-9da6-43c1cf348cc0"),
                            CreatedBy = "wgenghis",
                            CreatedOn = new DateTime(2019, 11, 19, 4, 11, 0, 0, DateTimeKind.Unspecified),
                            Description = "An epic fantasy trilogy set in the fictional world of Middle-earth.",
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("ebde1cdd-35f3-4ea6-8984-0d7d1302e257"),
                            CreatedBy = "aeinstein",
                            CreatedOn = new DateTime(2002, 8, 7, 16, 27, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fantasy novel that serves as a prequel to The Lord of the Rings.",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("5a176e35-fd4e-4ae0-8f6b-709eeaaa2827"),
                            CreatedBy = "mcurie",
                            CreatedOn = new DateTime(2014, 7, 12, 1, 41, 0, 0, DateTimeKind.Unspecified),
                            Description = "A collection of mythopoeic works exploring the mythology of Middle-earth.",
                            Title = "The Silmarillion"
                        },
                        new
                        {
                            Id = new Guid("b0e60fb8-a198-4b27-a935-54aa02d07a2c"),
                            CreatedBy = "alincoln",
                            CreatedOn = new DateTime(2001, 6, 18, 22, 1, 0, 0, DateTimeKind.Unspecified),
                            Description = "The first book in the popular Harry Potter series.",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = new Guid("68fcf3ea-711a-4a91-943c-8df2bab7746d"),
                            CreatedBy = "ntesla",
                            CreatedOn = new DateTime(2014, 12, 3, 20, 42, 0, 0, DateTimeKind.Unspecified),
                            Description = "A companion book to the Harry Potter series, featuring magical creatures.",
                            Title = "Fantastic Beasts and Where to Find Them"
                        },
                        new
                        {
                            Id = new Guid("1d2eb21a-7f00-440e-8d91-af1f373124c6"),
                            CreatedBy = "wshakespeare",
                            CreatedOn = new DateTime(2000, 8, 10, 1, 52, 0, 0, DateTimeKind.Unspecified),
                            Description = "A psychological novel exploring the moral and psychological struggles of its main character.",
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("8201ad58-0097-4852-adbb-38046938595b"),
                            CreatedBy = "ldavinci",
                            CreatedOn = new DateTime(2012, 5, 25, 18, 44, 0, 0, DateTimeKind.Unspecified),
                            Description = "A gripping novel set in the Deep South during the era of racial inequality.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("06783e47-d5d5-43c6-b75e-d3b4ae2b7cae"),
                            CreatedBy = "wshakespeare",
                            CreatedOn = new DateTime(2011, 3, 13, 10, 16, 0, 0, DateTimeKind.Unspecified),
                            Description = "A novel set in the 1950s and considered a sequel to To Kill a Mockingbird.",
                            Title = "Go Set a Watchman"
                        },
                        new
                        {
                            Id = new Guid("17d9e08f-1a3d-4148-9521-69cbc3f00018"),
                            CreatedBy = "mcurie",
                            CreatedOn = new DateTime(2008, 1, 9, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            Description = "A dystopian novel that explores the dangers of totalitarianism.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("b0110f8d-a9db-44b3-9373-91e7b3006e61"),
                            CreatedBy = "ntesla",
                            CreatedOn = new DateTime(2000, 5, 23, 16, 24, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic romantic novel set in 19th-century England.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("7e10a5f0-32f3-489c-ac99-468b400a3757"),
                            CreatedBy = "aeinstein",
                            CreatedOn = new DateTime(2012, 6, 27, 23, 44, 0, 0, DateTimeKind.Unspecified),
                            Description = "A story of wealth, love, and the American Dream during the Roaring Twenties.",
                            Title = "The Great Gatsby"
                        });
                });

            modelBuilder.Entity("Books.Domain.BookAggregate.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1480198c-b786-447b-8c10-d068f0988192"),
                            Bio = "George Raymond Richard Martin, commonly known as George R.R. Martin, is an American novelist and short story writer. He is best known for his series of epic fantasy novels, 'A Song of Ice and Fire', which has been adapted into the television series 'Game of Thrones'. Martin's writing is known for its complex characters, intricate plotlines, and realistic portrayal of political and social dynamics. His work has garnered critical acclaim and has a vast and dedicated fanbase.",
                            FirstName = "George R.R.",
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = new Guid("e026f2c2-bd9d-4f3d-95a7-3411eec89a4d"),
                            Bio = "An English writer, poet, and philologist.",
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = new Guid("7482e7b2-1c57-4d29-825d-5d5e58f5301c"),
                            Bio = "An English writer and the son of J.R.R. Tolkien.",
                            FirstName = "Christopher",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            Id = new Guid("44390cc5-3f32-4df6-aab3-39480f87788a"),
                            Bio = "A British author best known for the Harry Potter series.",
                            FirstName = "J.K.",
                            LastName = "Rowling"
                        },
                        new
                        {
                            Id = new Guid("d6a62e9d-af3a-4c7d-80fa-2612215f9af4"),
                            Bio = "A Russian novelist and philosopher.",
                            FirstName = "Fyodor",
                            LastName = "Dostoevsky"
                        },
                        new
                        {
                            Id = new Guid("e9715948-560f-4e50-8965-7cd61c480768"),
                            Bio = "An American novelist best known for her acclaimed work.",
                            FirstName = "Harper",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = new Guid("87229a28-033d-4f85-af7c-0e5aaaa1e49c"),
                            Bio = "An English author known for his political and social commentary.",
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = new Guid("78b58114-1fc0-4f9c-b5f4-2b16d352f543"),
                            Bio = "An English novelist known for her witty and insightful writing.",
                            FirstName = "Jane",
                            LastName = "Austen"
                        },
                        new
                        {
                            Id = new Guid("90118e72-df25-4e1e-ac27-35e15533daa0"),
                            Bio = "An American writer associated with the Jazz Age.",
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        });
                });

            modelBuilder.Entity("Books.Domain.BookAggregate.Entities.AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("AuthorBooks");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("1480198c-b786-447b-8c10-d068f0988192"),
                            BookId = new Guid("5485c003-57cc-4628-a1b8-34ccbe35c587"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1291)
                        },
                        new
                        {
                            AuthorId = new Guid("1480198c-b786-447b-8c10-d068f0988192"),
                            BookId = new Guid("7c838a53-cac5-4ebe-94cb-c9b46c537c4e"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1296)
                        },
                        new
                        {
                            AuthorId = new Guid("1480198c-b786-447b-8c10-d068f0988192"),
                            BookId = new Guid("0881e81c-fbfc-47ff-bc0d-5670aca11601"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1297)
                        },
                        new
                        {
                            AuthorId = new Guid("1480198c-b786-447b-8c10-d068f0988192"),
                            BookId = new Guid("7ca4a6d0-1f6d-4bd5-9d60-16e48a39563b"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1299)
                        },
                        new
                        {
                            AuthorId = new Guid("1480198c-b786-447b-8c10-d068f0988192"),
                            BookId = new Guid("9407e459-042d-48f0-a9ec-3abf49b81649"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1300)
                        },
                        new
                        {
                            AuthorId = new Guid("e026f2c2-bd9d-4f3d-95a7-3411eec89a4d"),
                            BookId = new Guid("8f33b67c-5080-4132-9da6-43c1cf348cc0"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1301)
                        },
                        new
                        {
                            AuthorId = new Guid("7482e7b2-1c57-4d29-825d-5d5e58f5301c"),
                            BookId = new Guid("8f33b67c-5080-4132-9da6-43c1cf348cc0"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1303)
                        },
                        new
                        {
                            AuthorId = new Guid("e026f2c2-bd9d-4f3d-95a7-3411eec89a4d"),
                            BookId = new Guid("ebde1cdd-35f3-4ea6-8984-0d7d1302e257"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1304)
                        },
                        new
                        {
                            AuthorId = new Guid("e026f2c2-bd9d-4f3d-95a7-3411eec89a4d"),
                            BookId = new Guid("5a176e35-fd4e-4ae0-8f6b-709eeaaa2827"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1305)
                        },
                        new
                        {
                            AuthorId = new Guid("44390cc5-3f32-4df6-aab3-39480f87788a"),
                            BookId = new Guid("b0e60fb8-a198-4b27-a935-54aa02d07a2c"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1306)
                        },
                        new
                        {
                            AuthorId = new Guid("44390cc5-3f32-4df6-aab3-39480f87788a"),
                            BookId = new Guid("68fcf3ea-711a-4a91-943c-8df2bab7746d"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1307)
                        },
                        new
                        {
                            AuthorId = new Guid("d6a62e9d-af3a-4c7d-80fa-2612215f9af4"),
                            BookId = new Guid("1d2eb21a-7f00-440e-8d91-af1f373124c6"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1308)
                        },
                        new
                        {
                            AuthorId = new Guid("e9715948-560f-4e50-8965-7cd61c480768"),
                            BookId = new Guid("8201ad58-0097-4852-adbb-38046938595b"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1309)
                        },
                        new
                        {
                            AuthorId = new Guid("e9715948-560f-4e50-8965-7cd61c480768"),
                            BookId = new Guid("06783e47-d5d5-43c6-b75e-d3b4ae2b7cae"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1310)
                        },
                        new
                        {
                            AuthorId = new Guid("87229a28-033d-4f85-af7c-0e5aaaa1e49c"),
                            BookId = new Guid("17d9e08f-1a3d-4148-9521-69cbc3f00018"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1311)
                        },
                        new
                        {
                            AuthorId = new Guid("78b58114-1fc0-4f9c-b5f4-2b16d352f543"),
                            BookId = new Guid("b0110f8d-a9db-44b3-9373-91e7b3006e61"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1312)
                        },
                        new
                        {
                            AuthorId = new Guid("90118e72-df25-4e1e-ac27-35e15533daa0"),
                            BookId = new Guid("7e10a5f0-32f3-489c-ac99-468b400a3757"),
                            CreatedAt = new DateTime(2023, 5, 16, 18, 26, 9, 457, DateTimeKind.Utc).AddTicks(1313)
                        });
                });

            modelBuilder.Entity("Books.Domain.BookAggregate.Entities.BookReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookReviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d23337f-a760-4685-8ef4-42952fa64a7b"),
                            BookId = new Guid("5485c003-57cc-4628-a1b8-34ccbe35c587"),
                            Comment = "Great book, highly recommended!",
                            Username = "alincoln"
                        },
                        new
                        {
                            Id = new Guid("993a5f82-f2a3-4e80-930d-8baf047b36bc"),
                            BookId = new Guid("5485c003-57cc-4628-a1b8-34ccbe35c587"),
                            Comment = "I couldn't put it down, fantastic read!",
                            Username = "jcaesar"
                        },
                        new
                        {
                            Id = new Guid("e7e6c93b-47e3-4b1b-8384-caaa8284c347"),
                            BookId = new Guid("7c838a53-cac5-4ebe-94cb-c9b46c537c4e"),
                            Comment = "An epic tale with intricate plot twists.",
                            Username = "aeinstein"
                        },
                        new
                        {
                            Id = new Guid("3baa7952-3374-4f05-9618-33e999acb928"),
                            BookId = new Guid("7c838a53-cac5-4ebe-94cb-c9b46c537c4e"),
                            Comment = "Captivating and immersive, loved every page.",
                            Username = "mcurie"
                        },
                        new
                        {
                            Id = new Guid("77110fa4-f4a1-4e76-9774-02455fe9e2e7"),
                            BookId = new Guid("8f33b67c-5080-4132-9da6-43c1cf348cc0"),
                            Comment = "A masterpiece of fantasy literature.",
                            Username = "ldavinci"
                        },
                        new
                        {
                            Id = new Guid("8bd2faa0-5738-465f-be31-06e72a4e95e6"),
                            BookId = new Guid("ebde1cdd-35f3-4ea6-8984-0d7d1302e257"),
                            Comment = "Beautifully written, a timeless classic.",
                            Username = "wshakespeare"
                        },
                        new
                        {
                            Id = new Guid("529f960d-c0eb-49c6-8b4f-2b18c599c39b"),
                            BookId = new Guid("5a176e35-fd4e-4ae0-8f6b-709eeaaa2827"),
                            Comment = "Intriguing characters and rich storytelling.",
                            Username = "ccleopatra"
                        },
                        new
                        {
                            Id = new Guid("d1f9368d-7961-4fd1-af22-c6c06f773d14"),
                            BookId = new Guid("5a176e35-fd4e-4ae0-8f6b-709eeaaa2827"),
                            Comment = "A fascinating journey through Middle-earth.",
                            Username = "aalexander"
                        },
                        new
                        {
                            Id = new Guid("a8e14588-aeb2-4459-b792-474bcb014066"),
                            BookId = new Guid("b0e60fb8-a198-4b27-a935-54aa02d07a2c"),
                            Comment = "Magical and enchanting, a must-read for all ages.",
                            Username = "ntesla"
                        },
                        new
                        {
                            Id = new Guid("7e249198-9d24-4024-93ca-f342c35e36d3"),
                            BookId = new Guid("b0e60fb8-a198-4b27-a935-54aa02d07a2c"),
                            Comment = "Thought-provoking and profound.",
                            Username = "wgenghis"
                        },
                        new
                        {
                            Id = new Guid("467f736e-0fb5-42a5-ab51-bcf6d6629d32"),
                            BookId = new Guid("1d2eb21a-7f00-440e-8d91-af1f373124c6"),
                            Comment = "A gripping and powerful novel.",
                            Username = "alincoln"
                        },
                        new
                        {
                            Id = new Guid("aae94120-0087-48a1-8537-d61b7068e5b8"),
                            BookId = new Guid("1d2eb21a-7f00-440e-8d91-af1f373124c6"),
                            Comment = "This book changed my perspective on life.",
                            Username = "jcaesar"
                        },
                        new
                        {
                            Id = new Guid("414eecf8-a7d9-4e6c-847c-8492c4b6353f"),
                            BookId = new Guid("8201ad58-0097-4852-adbb-38046938595b"),
                            Comment = "A classic that stands the test of time.",
                            Username = "aeinstein"
                        },
                        new
                        {
                            Id = new Guid("5b4f0137-7810-4e7c-8a74-41eead28a1dc"),
                            BookId = new Guid("8201ad58-0097-4852-adbb-38046938595b"),
                            Comment = "A remarkable and poignant story.",
                            Username = "mcurie"
                        },
                        new
                        {
                            Id = new Guid("84a87346-2e80-4594-82ba-2f09fe71bebe"),
                            BookId = new Guid("17d9e08f-1a3d-4148-9521-69cbc3f00018"),
                            Comment = "An unsettling and thought-provoking dystopian tale.",
                            Username = "ldavinci"
                        },
                        new
                        {
                            Id = new Guid("b677b2ca-322f-4543-85f7-1ea8e93b4d20"),
                            BookId = new Guid("b0110f8d-a9db-44b3-9373-91e7b3006e61"),
                            Comment = "A delightful and engaging romance.",
                            Username = "wshakespeare"
                        },
                        new
                        {
                            Id = new Guid("20a2f45a-b6f0-4c41-b7b3-458c7632ac99"),
                            BookId = new Guid("7e10a5f0-32f3-489c-ac99-468b400a3757"),
                            Comment = "An iconic representation of the Jazz Age.",
                            Username = "ccleopatra"
                        });
                });

            modelBuilder.Entity("Books.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b6eda7b-7ffb-4031-ad4d-90590c91d3ce"),
                            Email = "lincoln.abraham@example.com",
                            FirstName = "Abraham",
                            LastName = "Lincoln",
                            Password = "AQAAAAIAAYagAAAAENjKNRElvP5XUWfmhbpzCLpvWaAd1fCgCJOJQ/2/I8VWqluPBTpC76YtE3Cu7Usw9w==",
                            UserName = "alincoln"
                        },
                        new
                        {
                            Id = new Guid("20a8e0ea-e5be-4933-bf24-634395321e4d"),
                            Email = "caesar.julius@example.com",
                            FirstName = "Julius",
                            LastName = "Caesar",
                            Password = "AQAAAAIAAYagAAAAEJlXx19Siv0fTfKFNz8bWzwKrHr3M40Wlr/17A2T0XUinu+wPKdhFJyWjrQD0uN1kQ==",
                            UserName = "jcaesar"
                        },
                        new
                        {
                            Id = new Guid("e06f0e3d-6a26-4495-bdbf-763e8dc49400"),
                            Email = "einstein.albert@example.com",
                            FirstName = "Albert",
                            LastName = "Einstein",
                            Password = "AQAAAAIAAYagAAAAENnIWf5ct4xPjNWUD77Ep21+miK2z4Yh4OHFAS9h+FDld7gVM6OJVbvJnaD/OBVVBA==",
                            UserName = "aeinstein"
                        },
                        new
                        {
                            Id = new Guid("d1c6720f-38b1-46c9-8907-1b7b7c41eadb"),
                            Email = "curie.marie@example.com",
                            FirstName = "Marie",
                            LastName = "Curie",
                            Password = "AQAAAAIAAYagAAAAEB4uxGp6GUucmKAYOxNlDeufRg3aTuLary8z9SJjiOcEn8h5ks45oRpf9GI7OrFwRg==",
                            UserName = "mcurie"
                        },
                        new
                        {
                            Id = new Guid("67268812-e309-4ac9-bd1d-c9229eb69817"),
                            Email = "davinci.leonardo@example.com",
                            FirstName = "Leonardo",
                            LastName = "da Vinci",
                            Password = "AQAAAAIAAYagAAAAEGtcQaTtDoAGVFxOoVWay8M46f/N3FZhE8/sPCZH8U8Y/uYvrH2hHuoF9fDvRzRQEg==",
                            UserName = "ldavinci"
                        },
                        new
                        {
                            Id = new Guid("dc85a3d5-cb0e-4bc1-b3cd-8e4c4dde3913"),
                            Email = "shakespeare.william@example.com",
                            FirstName = "William",
                            LastName = "Shakespeare",
                            Password = "AQAAAAIAAYagAAAAENLvWBQPKPOmuxr1cDeOxO+giWA/P+kXKJxjKnrsoeQ5dY0fKigZhI93Z1yhA9bCDQ==",
                            UserName = "wshakespeare"
                        },
                        new
                        {
                            Id = new Guid("9a86f182-fef7-46f8-b71a-ac6ea2068633"),
                            Email = "cleopatra@example.com",
                            FirstName = "Cleopatra",
                            LastName = "",
                            Password = "AQAAAAIAAYagAAAAECNNQKRjoc1FwqJz19kkFCplW0KLpmP/TQjuEwz5WBs0i/MzxDjgk7ZYS5xGtGU6bA==",
                            UserName = "ccleopatra"
                        },
                        new
                        {
                            Id = new Guid("f8cd6f8d-a49c-4d96-9723-0095c0daeb37"),
                            Email = "alexander@example.com",
                            FirstName = "Alexander",
                            LastName = "the Great",
                            Password = "AQAAAAIAAYagAAAAEBxG4JlJGKOUB/zUGkam6GI4JrbRoMeOjW/wqnUoK2ObG77tGhGzlHjiQtCQ4qAC2Q==",
                            UserName = "aalexander"
                        },
                        new
                        {
                            Id = new Guid("5cf7827d-1d79-4ab9-b0c8-564913450e77"),
                            Email = "tesla.nikola@example.com",
                            FirstName = "Nikola",
                            LastName = "Tesla",
                            Password = "AQAAAAIAAYagAAAAEEK2HlKj3mO8OqqV4Y6P8jrjn/g5iH4bfp6RUXyMhXJB2xp+yGvtuPJD7qf/S/kSsw==",
                            UserName = "ntesla"
                        },
                        new
                        {
                            Id = new Guid("42b8c308-1aaa-4038-8201-fdd835527472"),
                            Email = "genghis.khan@example.com",
                            FirstName = "Genghis",
                            LastName = "Khan",
                            Password = "AQAAAAIAAYagAAAAEDOqf/bmA7tTtRmAuN+50C/6ZpmW/UEf7bDSPUckoqW7V1NjTFK6CjtN9uoay2Nmgg==",
                            UserName = "wgenghis"
                        });
                });

            modelBuilder.Entity("Books.Domain.BookAggregate.Entities.AuthorBook", b =>
                {
                    b.HasOne("Books.Domain.BookAggregate.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Books.Domain.BookAggregate.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Books.Domain.BookAggregate.Entities.BookReview", b =>
                {
                    b.HasOne("Books.Domain.BookAggregate.Book", null)
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Books.Domain.BookAggregate.Book", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
